### ISSUE TITLE
Possible bug in anomaly_detection.py

### ISSUE THREAD

**Issue by shyam1998** [arunppsg/TadGAN#3]
In anomaly_detection.py line 105, you calculate the standard deviation of the mean value (which is a scalar) and it makes no sense. I think it should be `window_std = np.std(window_elts)`

**Comment by arunppsg** [comment]
Yes, you are right. Need to fix it. Will you be interested in fixing it?

**Comment by shyam1998** [comment]
@arunppsg I just made a pull request.

**Comment by arunppsg** [comment]
Thanks for it. Will close this issue.
