### ISSUE TITLE
How to use other datasets for TadGAN?

### ISSUE THREAD

**Issue by kanesp** [arunppsg/TadGAN#6]
* Python version:3.6
* Operating System:Ubuntu 18.04.5 LTS

### Description
The dataset for ur code  should have a column name as signal containing the signals and a column with name anomaly containing the true labels.  But in the paper of TADGAN, e.g.,NAB(Art)  dataset is only has two COLUMN ( timestamp and value). how can i use the dataset like NAB?

**Comment by arunppsg** [comment]
The anomaly column is only required for validation purpose. See point 1 in [usage](https://github.com/arunppsg/TadGAN#usage).

**Comment by kanesp** [comment]
thanks.

**Comment by kanesp** [comment]
i find the anomaly column is used in anomaly_detection.test(test_loader, encoder, decoder, critic_x) which is used to detect anomalies. if i want to detect anomalies, my dataset must have the anomaly column. Right?
